import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import Graph from "@/components/graph";
import tabsArray from "@/constant/tabs-array";
import useAppDispatch from "@/store/hooks/use-dispatch";
import tabsSlice from "@/store/slices/tabs";

const inter = Inter({ subsets: ["latin"] });

function Home() {
  const dispatch = useAppDispatch();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.graphtab}>
        <div className={styles.tabs}>
          <ul>
            {tabsArray.map((item, index) => {
              return (
                <li
                  key={index}
                  onClick={() =>
                    dispatch(tabsSlice.actions.updateTab(item.label))
                  }
                >
                  <button>{item.label}</button>
                </li>
              );
            })}
          </ul>
        </div>
        <div className={styles.reactgraph}>
          <Graph />
        </div>
      </div>
    </>
  );
}

export default Home;
