import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import Graph from "@/components/graph";
import { catOne, catTwo } from "@/constant/tabs-array";
import useAppDispatch from "@/store/hooks/use-dispatch";
import tabsSlice from "@/store/slices/tabs";
import PinIcon from "@/components/icons/PinIcon";

const inter = Inter({ subsets: ["latin"] });

function Home() {
  const dispatch = useAppDispatch();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.graphtab}>
        <div className={styles.tabs}>
          <label className={styles.mainlabel}>Col1</label>
          <ul>
            <label className={styles.mainlabel1}>{catOne.name}</label>
            {catOne.category.map((item, index) => {
              return (
                <li
                  key={index}
                  onClick={() =>
                    dispatch(tabsSlice.actions.updateTab(item.label))
                  }
                >
                  <button>{item.label}</button>
                  <span>
                    <PinIcon />
                  </span>
                </li>
              );
            })}
          </ul>
          <ul>
            <label className={styles.mainlabel1}>{catTwo.name}</label>
            {catTwo.category.map((item, index) => {
              return (
                <li
                  key={index}
                  onClick={() =>
                    dispatch(tabsSlice.actions.updateTab(item.label))
                  }
                >
                  <button>{item.label}</button>
                  <span>
                    <PinIcon />
                  </span>
                </li>
              );
            })}
          </ul>
        </div>
        <div className={styles.raectselectbox}>
          <ul>
            <li>
              <select name="" id="">
                <option value="1">a</option>
                <option value="1">b</option>
                <option value="1">c</option>
              </select>
            </li>
            <li>
              <select name="" id="">
                <option value="1">d</option>
                <option value="1">e</option>
                <option value="1">f</option>
              </select>
            </li>
          </ul>
          <div className={styles.reactgraph}>
            <Graph />
          </div>
        </div>
      </div>
    </>
  );
}

export default Home;
